export const SET_CONNECTIONS = 'SET_CONNECTIONS';
export const SET_CONNECTIONS_ERROR = 'SET_CONNECTIONS_ERROR';
export const SET_CONNECTIONS_LOADING = 'SET_CONNECTIONS_LOADING';
export const SET_CONNECTIONS_SHOULD_SYNC = 'SET_CONNECTIONS_SHOULD_SYNC';
export const SET_CONNECTIONS_SYNCING = 'SET_CONNECTIONS_SYNCING';
export const CONNECTIONS_SHOULD_SYNC = 'CONNECTIONS_SHOULD_SYNC';

export default {
    SET_CONNECTIONS,
    SET_CONNECTIONS_LOADING,
    SET_CONNECTIONS_SYNCING,
    CONNECTIONS_SHOULD_SYNC,
};
