export const SET_RETRY_REQUEST = 'SET_RETRY_REQUEST';
export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS';
export const WAITING_ON_REQUEST = 'WAITING_ON_REQUEST';
export const NETWORK_STATUS_UPDATING = 'NETWORK_STATUS_UPDATING';
